language: android

sudo: false

branches:
  only: master

script: gradle :rsv_example:assembleRelease

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - platform-tools
    - tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

env:
  global:
  # define critical vars
  - secure: PzCt2l8yfDxtObEz5EawtjPw8ojmstnsivAmbp6cMpshT2qsrwBAItUCtE6xPt6eX3cCCKpnVSy1mAsz9Vbj2s/w9Pb7G6tZqiUrqmpIWKXwAUzInycIVrzHRAFyZzXa6uCIIwx5NhxhKaGUh/hXynpXXphWofaeZX+QommCvLw=
  - secure: lkO0z+g7FrcIGM8xp/r0l+TXI7NnpjrJ0dWFG8+bvV/Tm03LTH+M/eAYiMCNTcFQ1uKpZVROeAj9OSkBsX3JorLSTb/mBLcoqcscUUHoyOY3auok45QuWIAqPkwbByzlgFfrdpqSc3AfxHcbbY8YWhHOj2YggxtJkTLsxQl0gCM=

after_success:
  # run bintray upload straight after deploy
  - gradle bintrayUpload -PbintrayUser=USER -PbintrayKey=KEY -PdryRun=false