language: android

sudo: false

branches:
  only: master

script: gradle :rsv_example:assembleRelease

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23

    # Additional components
    - platform-tools
    - tools
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-x86-android-17

deploy:
  - ./gradle clean build bintrayUpload -PbintrayUser=USER -PbintrayKey=KEY -PdryRun=false

env:
  global:
  - secure: PzCt2l8yfDxtObEz5EawtjPw8ojmstnsivAmbp6cMpshT2qsrwBAItUCtE6xPt6eX3cCCKpnVSy1mAsz9Vbj2s/w9Pb7G6tZqiUrqmpIWKXwAUzInycIVrzHRAFyZzXa6uCIIwx5NhxhKaGUh/hXynpXXphWofaeZX+QommCvLw=
  - secure: d2MfgHvReYH+fA3sgkiAXNBPsnkPj/8h1N7V8Ly0tGbbaT15qC8OYN4hmuo6NdaUmkTMycJqRn9Bu9VP0MDvEL6+uGiaESsYcpkYoSoNyadSRyYt9L9XRcZw2I2GMejwZ9ma2UUQNDnqLGtGVQBMEPAzTQiFzO4L8PVzje3Gq5g=
